# Generated by Django 4.2.6 on 2023-10-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("silant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="service_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="silant.service",
            ),
        ),
    ]
